#!/bin/bash

gs  -dNOPAUSE -dBATCH -dSAFER \
    -sDEVICE=pdfwrite \
    -dCompatibilityLevel=1.5 \
    -dPDFSETTINGS=/screen \
    -dEmbedAllFonts=true \
    -dSubsetFonts=true \
    -dCompressFonts=true \
    -dConvertCMYKImagesToRGB=true \
    -dDownsampleColorImages=true \
    -dDownsampleGrayImages=true \
    -dDownsampleMonoImages=true \
    -dColorImageDownsampleType=/Bicubic \
    -dColorImageResolution=60 \
    -dGrayImageDownsampleType=/Bicubic \
    -dGrayImageResolution=60 \
    -dMonoImageDownsampleType=/Bicubic \
    -dMonoImageResolution=60 \
    -sOutputFile=$2 \
     $1